<?php
/**
 * @category   Softtek
 * @package    Softtek_Marketplace
 * @author     yordan@softtek.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Softtek\Marketplace\Model\ResourceModel;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class OrderReview extends AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('st_order_review', 'review_id');
    }
}
