<?php 
/**
* Purpletree_Marketplace marketplace
* NOTICE OF LICENSE
*
* This source file is subject to the Purpletree License that is bundled with this package in the file license.txt.
* It is also available through online at this URL: https://www.purpletreesoftware.com/license.html
*
* @category    Purpletree
* @package     Purpletree_Marketplace
* @author      Purpletree Software
* @copyright   Copyright (c) 2017
* @license     https://www.purpletreesoftware.com/license.html
*/
?>
<h1>Welcome to Marketplace!</h1>
<?php var_dump($this->getWelcomeTxt()); ?>