<!--
/**
* Purpletree_Marketplace shippingpolicy
* NOTICE OF LICENSE
*
* This source file is subject to the Purpletree License that is bundled with this package in the file license.txt.
* It is also available through online at this URL: https://www.purpletreesoftware.com/license.html
*
* @category    Purpletree
* @package     Purpletree_Marketplace
* @author      Purpletree Infotech Private Limited
* @copyright   Copyright (c) 2017
* @license     https://www.purpletreesoftware.com/license.html
*/
-->
<?php 
$storeData=$this->getStoreDetails(); 
?>
<div class="pts-container_aboutus">
	<div class="pts-aboutus">
		<p><?php echo $storeData['store_shipping_policy']; ?></p>
	</div>
</div>