<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_GDPR
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>

<div id="prgdpr-account-check" class="prgdpr" data-bind="scope: 'prgdpr-account-check-form'">
    <!-- ko template: getTemplate() --> <!-- /ko -->
</div>

<?php
$blockData = $block->getData('data');
$fromActionUrl = $block->escapeUrl($blockData['fromActionUrl']);
?>

<script type="text/x-magento-init">
   {
       "#prgdpr-account-check": {
           "Magento_Ui/js/core/app": {
               "components": {
                   "prgdpr-account-check-form": {
                       "component": "Plumrocket_GDPR\/js\/view\/account-check",
                       "fromActionUrl": <?= /* @noEscape */ json_encode($fromActionUrl) ?>
                   }
               }
           }
       }
   }
</script>
