<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_GDPR
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<form id="prgdpr-consents-form" method="post" action="<?= $block->escapeUrl($block->getUrl('prgdpr/consentcheckboxes/update')) ?>">
    <fieldset class="fieldset">
        <?= $block->getChildHtml('prgdpr_checkbox_my_account') ?>
        <div class="prgdpr-button-wrap">
            <button class="action primary" type="submit">
                <?= $block->escapeHtml(__('Update')) ?>
            </button>
            <button class="action submit" type="button" id="cancel-delete">
                <a href="<?= $block->escapeUrl($block->getData('backUrl')) ?>"><?= $block->escapeHtml(__('Cancel')) ?></a>
            </button>
        </div>
    </fieldset>
</form>
<script>
    require([
        'jquery',
        'loader'
    ], function ($) {
        var element = $('#prgdpr-consents-form');
        element.loader({icon: "<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"});
        element.loader('show');
    });
</script>
<script type="text/x-magento-init">
{
    "#prgdpr-consents-form": {
        "Plumrocket_GDPR/js/view/post-submit-form": {
            "disableLoaderOnCheckboxesInited": true
        }
    }
}
</script>
