<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_GDPR
 * @copyright   Copyright (c) 2018 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<?php
$_helper = $this->helper('Smartwave\Porto\Helper\Data');

$popup = $_helper->getConfig('porto_settings/newsletter');
if($popup['enable']) {
    $delay = $popup["delay"];
    ?>
    <script type="text/javascript">
        require([
            'jquery',
            'jquery/jquery.cookie',
            'fancybox/js/jquery.fancybox'
        ], function ($) {
            $(document).ready(function(){
                <?php if ($popup['enable'] == 1): ?>
                if($("body").hasClass("cms-index-index")) {
                    <?php endif; ?>
                    var check_cookie = $.cookie('newsletter_popup');
                    if(window.location!=window.parent.location){
                        $('#newsletter_popup').remove();
                    } else {
                        if(check_cookie == null || check_cookie == 'shown') {
                            setTimeout(function(){
                                beginNewsletterForm();
                            }, <?= /* @noEscape */ $delay ?>);
                        }
                        $('#newsletter_popup_dont_show_again').on('change', function(){
                            if($(this).length){
                                var check_cookie = $.cookie('newsletter_popup');
                                if(check_cookie == null || check_cookie == 'shown') {
                                    $.cookie('newsletter_popup','dontshowitagain');
                                }
                                else
                                {
                                    $.cookie('newsletter_popup','shown');
                                    beginNewsletterForm();
                                }
                            } else {
                                $.cookie('newsletter_popup','shown');
                            }
                        });
                    }
                    <?php if ($popup['enable'] == 1): ?>
                }
                <?php endif; ?>
            });

            function beginNewsletterForm() {
                $.fancybox({
                    'padding': '0px',
                    'autoScale': true,
                    'transitionIn': 'fade',
                    'transitionOut': 'fade',
                    'type': 'inline',
                    'href': '#newsletter_popup',
                    'onComplete': function() {
                        $.cookie('newsletter_popup', 'shown');
                    },
                    'tpl': {
                        closeBtn: '<a title="Close" class="fancybox-item fancybox-close fancybox-newsletter-close" href="javascript:;"></a>'
                    },
                    'helpers': {
                        overlay: {
                            locked: false
                        }
                    }
                });
                $('#newsletter_popup').trigger('click');
            }
        });
    </script>
    <style type="text/css">
        <?php
            if($popup["custom_style"]){
                /* @noEscape */ echo $popup["custom_style"];
            }
        ?>
        #newsletter_popup{
        <?php
            if($popup["width"]){
                /* @noEscape */ echo "width:".$popup["width"].";";
            }
            if($popup["height"]){
                /* @noEscape */ echo "height:".$popup["height"].";";
            }
            if($popup["bg_color"]){
                /* @noEscape */ echo "background-color:".$popup["bg_color"].";";
            }
            if(isset($popup["bg_image"]) && $popup["bg_image"]){
                $folderName = \Smartwave\Porto\Model\Config\Backend\Image\Newsletterbg::UPLOAD_DIR;
                $path = $folderName . '/' . $popup["bg_image"];
                $imageUrl = $_helper->getBaseUrl() . $path;
        ?>
            background-image:url(<?= $block->escapeUrl($imageUrl) ?>);
        <?php
            }
        ?>
        }
    </style>
    <div class="newsletter" id="newsletter_popup" style="display: none;">
        <div class="block-content">
            <?php
            if(isset($popup["logo_src"]) && $popup["logo_src"]){
                $folderName = \Smartwave\Porto\Model\Config\Backend\Image\Newsletterlogo::UPLOAD_DIR;
                $path = $folderName . '/' . $popup["logo_src"];
                $logoUrl = $_helper->getBaseUrl() . $path;
                ?>
                <img src="<?= $block->escapeUrl($logoUrl) ?>" alt="" />
                <?php
            }
            ?>
            <?= /* @noEscape */ $popup["content"] ?>
            <form class="form subscribe"
                  novalidate
                  action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                  method="post"
                  data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                  id="newsletter-popup-validate-detail">
                <div class="field newsletter">
                    <div class="control">
                        <input name="email" type="email" id="newsletter-popup"
                               data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <?= $block->getChildHtml('prgdpr_porto_newsletter_popup') ?>
                <div class="actions">
                    <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Go')) ?>" type="submit">
                        <span><?= $block->escapeHtml(__('Go')) ?></span>
                    </button>
                </div>
            </form>
            <div class="subscribe-bottom">
                <input type="checkbox" id="newsletter_popup_dont_show_again"/>
                <label for="newsletter_popup_dont_show_again"><?= $block->escapeHtml(__("Don't show this popup again")) ?></label>
            </div>
        </div>
    </div>
    <?php
}
?>
