<!--
/**
* Purpletree_Marketplace becomeseller
* NOTICE OF LICENSE
*
* This source file is subject to the Purpletree License that is bundled with this package in the file license.txt.
* It is also available through online at this URL: https://www.purpletreesoftware.com/license.html
*
* @category    Purpletree
* @package     Purpletree_Marketplace
* @author      Purpletree Infotech Private Limited
* @copyright   Copyright (c) 2017
* @license     https://www.purpletreesoftware.com/license.html
*/
-->
<?php
	$storeData=$this->getStoreDetails();
	$isSeller=$this->getIsSeller();
?>
<form class="form becomeseller" data-mage-init='{"validation": {}}' action="<?php echo $this->getUrl('*/*/sellersave') ?>" id="becomeseller-form" method="post" data-hasrequired="* Required Fields" novalidate="novalidate" enctype="multipart/form-data" >
	<?php echo $this->getBlockHtml('formkey')?>
    <fieldset class="fieldset" >
		<div class="fields">
			<?php
				if($storeData==''){
			?>

			<div class="beseller">
				<div class="besellerchk" style="display: none;">
					<input type="checkbox" id="seller-check" class="seller-check" name="is_seller" title="<?php echo __('Become a Seller') ?>" value="1" checked="checked" >
					<label for="seller-check" name="seller_label" class="label"><span><?php echo __('Become a Seller') ?></span></label>
				</div>
				<br/>
				<div class="besellerurl required" style="display:none;">
					<label for="store-url" name="seller_label" class="label"><span><?php echo __('Store Url') ?></span><span style="color:red"><?php  echo __('*') ?></span></label>
					<br/>
					<input type="text" id="store-url" class="store-url validate-code" name="store_url" data-validate="{'required':true, 'no-whitespace':true}" >
					<p style="font-size: 11px;padding-top: 3px;"><?php  echo __('Enter Unique Alphanumeric Storeurl to be used as your URL.') ?></p>
					<div class="errormsg"  style=" color: #e02b27;font-size: 12px;">
					</div>
				</div>
			</div>

			<?php
				}
				else {
					if($storeData['status_id']==0 && $isSeller==0){
			?>
					<div class="beseller">
						<div class="besellerchk">
							<label for="seller-check" name="seller_label_again" class="label"><span><?php echo __('Your seller account has been removed previously, so to again add as seller please select yes') ?></span></label><br>
							<input checked type="radio" data-validate="{'validate-one-required-by-name':true}" id="agseller" name="agseller" value="1" ><?php echo __('Yes'); ?>. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
							<input type="radio" data-validate="{'validate-one-required-by-name':true}"  name="agseller" value="0"> <?php echo __('No'); ?>. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
						</div>
					</div>
						<style>
					#sellersubmit {
						display:block !important;
					}
					</style>
					<?php
					}if($storeData['status_id']==0 && $isSeller==1) {
					?>
					<div class="pts-waitingmsg">
						<div class="pts-waitingmsg-block">
							<label name="seller_label" class="label"><span><?php echo __('Waiting for admin approval') ?></span></label><br>
						</div>
					</div>
					<style>
					.pts-seller-submit {
						display:none !important;
					}
					</style>
			<?php
					}
					}
			?>
			<input name="again_seller" id="again_seller" value="<?php echo $storeData=='' ? 0:1;?>" type="hidden">
			<input name="seller_id" id="seller_id" value="<?php echo $storeData=='' ? '':$storeData['seller_id'];?>" type="hidden">
		</div>
    </fieldset>
	<?php //if(isset($storeData) && ($storeData['status_id'] == 0 && $isSeller==1)) { } else {?>
    <div class="actions-toolbar">
        <div class="primary">
            <input name="hideit" id="hideit" value="" type="hidden">
            <button style="display:none" type="submit" title="Submit" id="sellersubmit" class="action submit primary pts-seller-submit pts-newbtn-next">
                <span><?php echo __('Submit'); ?></span>
            </button>
        </div>
    </div>
	<?php //} ?>


</form>

<script type="text/javascript">
	require(['jquery', 'jquery/ui'], function($){
	$(document).ready(function(){
        $('.besellerurl').css('display', 'block');
        $('.pts-seller-submit').css('display', 'block');
    });
	$(document).ready(function(){
			 $('form.becomeseller button.submit').on('click', function() {
				if($('#agseller').is(":checked")){
					return true;
				}
		//$('.store-url').blur(function(){
			var testing = false;
			if($('.seller-check').is(":checked")){
			var storeurl=$("#store-url").val();
			if(storeurl!='')
			{
				$.ajax({
					url: "<?php echo $this->getUrl('marketplace/index/sellerunique'); ?>",
					dataType: "json",
					showLoader: true,
					data:'store_url='+storeurl,
					type: 'POST',
					success: function (result) {
						if(result!=0)
						{
							$('.errormsg').css('display', 'block');
							$('.errormsg').html('<span><?php echo __("Enter Unique Store URL"); ?></span>');
							//$('#sellersubmit').prop('disabled', true);

						}
						else
						{
							 testing = true;
							 $('form.becomeseller').submit();
							$('.errormsg').css('display', 'none');
							//$('#sellersubmit').prop('disabled', false);
						}
					}
				});
			} else {
									$('.errormsg').css('display', 'block');
									$('.errormsg').html('<span><?php echo __("Store URL Required"); ?></span>');
				}
			}
			 return testing;
		});
		/* $('.store-url').click(function(){
			$('#sellersubmit').prop('disabled', true);

		}); */
        });
});
</script>
