<!--
/**
* Purpletree_Marketplace orderview
* NOTICE OF LICENSE
*
* This source file is subject to the Purpletree License that is bundled with this package in the file license.txt.
* It is also available through online at this URL: https://www.purpletreesoftware.com/license.html
*
* @category    Purpletree
* @package     Purpletree_Marketplace
* @author      Purpletree Infotech Private Limited
* @copyright   Copyright (c) 2017
* @license     https://www.purpletreesoftware.com/license.html
*/
-->
<?php
	$billingAddress		= $this->getBillingAddress();
	$shippingAddress	= $this->getShippingAddress();
	$paymentMethod		= $this->getPaymentMethod();
	$cursymbol 			= $this->getCurrentCurrencySymbol();
    $orderCollection   	= $this->getOrderCollection();
	$manageOrder 		= $this->manageOrder();
	$productCollection  = $this->getProductCollection();
	$getSellerShipping  = $this->getSellerShipping();
	$pathInvoice		= $this->getInvoiceUrl($orderCollection['entity_id']);
    $currentCustomer = $block->getData("customer_view_model")->getCurrentCustomer();
    $_order = $block->getOrder();
    $cancelRequestData = $block->getData("customer_view_model")->getCancelRequestData();
?>
<div class="order-date datechng">
    <p><b><?php echo  __("Order Date :").' '.date('d/',strtotime($orderCollection['created_at'])).''. __(date("F",strtotime($orderCollection['created_at']))).''.date("/Y",strtotime($orderCollection['created_at']));?></b>
        <?php if ($manageOrder) { ?>
            <?php if(!$this->getSellerorderInvoice()) { ?>
                <b>	<a class="pts-order-statuslink"href="<?php echo $this->getUrl('marketplace/index/invoicegenerate', ['order_id' => $orderCollection['entity_id']]); ?>"><?php echo __('Gerar fatura') ?></a></b>
            <?php }?>
            <?php if ($currentCustomer->getIsSeller() && $_order->getStatus() == 'cancelamento_solicitado' || 'devolucao_solicitado' && count($cancelRequestData)): ?>
                <a href="#" class="action authorize-cancel" style="float: right; margin-right: 10px;">
                    <strong>
                        <?= /* @escapeNotVerified */ __('Authorize cancellation or refund') ?>
                    </strong>
                </a>
            <?php endif ?>
        <?php } ?>
    </p>
        <div class="pts-order-status">
		<p>
			<b class="pts-order-statustxt"><?php echo __("Status do pedido") ?><?php echo ': '.strtoupper($_order->getStatusLabel());?></b>

			<!-- <b style="float:right;" class="pts-order-statustxt">< ?php echo __("Admin order status :") ?>< ?php echo ' : '.strtoupper($this->getStatusOptio($orderCollection['status']));?></b> -->
		</p>
	</div>
</div>
<ul class="items order-links">
	<li class="nav item current"><strong><?php echo __('Items Ordered') ?></strong></li>
	<?php if($this->getSellerorderInvoice()) { ?>
	<?php //if($orderCollection['state']=='complete'){?>
		<li class="nav item"><a href="<?php echo $pathInvoice; ?>"><?php echo __('Invoice') ?></a></li>
	<?php } ?>
</ul>
<div class="order-details-items ordered">
	<div class="table-wrapper order-items" >
		<table id="my-orders-table" class="data table table-order-items" summary="Items Ordered" >
			<caption class="table-caption"><?php echo __('Items Ordered') ?></caption>
			<thead>
				<tr>
					<th class="col name"><?php echo __('Product Name') ?></th>
					<th class="col sku"><?php echo __('SKU') ?></th>
					<th class="col price"><?php echo __('Price') ?></th>
					<th class="col qty"><?php echo __('Qty') ?></th>
						<th class="col tax"><?php echo __('Tax') ?></th>
					<th class="col amounnt"><?php echo __('Discount Amount') ?></th>
					<th class="col subtotal"><?php echo __('Subtotal') ?></th>
				</tr>
			</thead>
			<?php foreach ($productCollection as $productData){ ?>
			<?php //$productData = $product->getData(); ?>
				<tbody>
					<tr  id="order-item-row-36">
						<td class="col name" data-th="Product Name"><?php echo $productData['name']; ?></td>
						<td class="col sku" data-th="SKU"><?php echo $productData['sku']; ?></td>
						<td class="col price" data-th="Price">

								<span class="price"><?php echo $this->getCurrencyData($productData['price']); ?></span>

						</td>
						<td class="col qty" data-th="Qty">
						<ul class="items-qty">
							<li class="item">
							<span class="content"><?php echo intval($productData['qty_ordered']);  ?></span>
							</li>
						</ul>
						</td>
						<td class="col tax" data-th="Tax">

								<span class="tax"><?php echo  $this->getCurrencyData($productData['tax_amount']); ?></span>

						</td>
						<td class="col discount" data-th="Discount">

								<span class="discount"><?php echo $this->getCurrencyData($productData['discount_amount']); ?></span>

						</td>
						<td class="col subtotal" data-th="Subtotal">
							<strong>
								<span class="price"><?php echo $this->getCurrencyData($productData['base_row_total_incl_tax']); ?></span>
							</strong>
						</td>
					</tr>
				</tbody>
			<?php }?>
			<tfoot>
			<?php if($getSellerShipping) { ?>
			<tr class="grand_total">
					<th class="mark" colspan="6" scope="row">
						<strong><?php echo __('Subtotal') ?></strong>
					</th>
					<td class="amount" data-th="Grand Total">
						<strong>
							<span class="price"><?php echo $this->getCurrencyData($this->getSellerOrderTotals()); ?></span>
						</strong>
					</td>
				</tr>
				<tr class="grand_total">
					<th class="mark" colspan="6" scope="row">
						<strong><?php echo __('Seller Shipping') ?></strong>
					</th>
					<td class="amount" data-th="Seller Shipping">
						<strong>
							<span class="price"><?php echo $this->getCurrencyData($this->getSellerShipping()); ?></span>
						</strong>
					</td>
				</tr>
				<tr class="grand_total">
					<th class="mark" colspan="6" scope="row">
						<strong><?php echo __('Grand Total') ?></strong>
					</th>
					<td class="amount" data-th="Grand Total">
						<strong>
							<span class="price"><?php echo $this->getCurrencyData($this->getSellerOrderTotals()+$this->getSellerShipping()); ?></span>
						</strong>
					</td>
				</tr>
			<?php } else { ?>
				<tr class="grand_total">
					<th class="mark" colspan="6" scope="row">
						<strong><?php echo __('Grand Total') ?></strong>
					</th>
					<td class="amount" data-th="Grand Total">
						<strong>
							<span class="price"><?php echo $this->getCurrencyData($this->getSellerOrderTotals()); ?></span>
						</strong>
					</td>
				</tr>
			<?php } ?>
			<tr><td colspan="8"><?php echo __('Fretes, desconto de pedido são excluídos dos totais.'); ?></td></tr>
			</tfoot>
	<form style="margin-top:20px;"class="form productoption" action="<?php echo $this->getUrl('marketplace/index/changeSellerStatus', ['order_id' => $orderCollection['entity_id']]); ?>" id="product-form" method="post" enctype="multipart/form-data">
		<?php echo $this->getBlockHtml('formkey')?>
    <fieldset class="fieldset" style="margin-bottom:15px;">
		<div class="fields">
			<div class="field seller_status required">
				<label class="label" for="seller_status"><span>Status atual do pedido</span></label>
				<div class="control">
					<select name="seller_status" class="" id="seller_status" data-validate="{required:true}" aria-required="true">
					<?php $statuslist = $this->getAvailableStatusesByCurrentOrder() ?>
					<?php foreach($statuslist as $status) { ?>
						<option <?php if($status['value'] == $this->getSellerOrderStatus2()) { ?> selected="selected" <?php } ?> value="<?php echo $status['value']; ?>"><?php echo $status['label']; ?></option>
					<?php } ?>
					</select>
				</div>
			</div>
            <div class="field seller_order_comment required" style="margin-bottom: 0px;">
                <label for="history_comment" class="admin__field-label">
                    <?= $block->escapeHtml(__('Comment')) ?>
                </label>
                <div class="admin__field-control">
                    <textarea name="history[comment]"
                        rows="3"
                        cols="5"
                        id="history_comment"
                        class="admin__control-textarea"></textarea>
                </div>
            </div>
            <div class="field seller_order_options required" style="display: none;">
                <difv class="order-history-comments-options">
                    <div class="admin__field admin__field-option">
                        <input name="history[is_customer_notified]"
                            type="checkbox"
                            id="history_notify"
                            class="admin__control-checkbox"
                            checked="checked"
                            value="1"/>
                        <label class="admin__field-label" for="history_notify">
                            <?= $block->escapeHtml(__('Notify Customer by Email')) ?>
                        </label>
                    </div>
                    <div class="admin__field admin__field-option">
                        <input name="history[is_visible_on_front]"
                            type="checkbox"
                            id="history_visible"
                            class="admin__control-checkbox"
                            checked="checked"
                            value="1" />
                        <label class="admin__field-label" for="history_visible">
                            <?= $block->escapeHtml(__('Visible on Storefront')) ?>
                        </label>
                    </div>
                </difv>
            </div>
		</div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary pts-review-box">
            <button type="submit" title="Submit" class="action submit primary pts-newbtn-next">
                <span>Salvar</span>
            </button>
        </div>
    </div>
</form>
		</table>
	</div>
</div>
<div class="block block-order-details-view">
	<div class="block-title">
		<strong><?php echo __('Order Information') ?></strong>
	</div>
	<div class="block-content">
	<?php if($shippingAddress) { ?>
		<div class="box box-order-shipping-address">
			<strong class="box-title">
				<span><?php echo __('Shipping Address') ?></span>
			</strong>
			<div class="box-content">
				<address>
					<?php echo $shippingAddress['firstname']." "; ?><?php echo $shippingAddress['lastname']; ?>
					<?php if($shippingAddress['street']!=''){echo '</br>'.$shippingAddress['street'];} ?></br>
					<?php echo $shippingAddress['city'].", "; ?><?php if($shippingAddress['region']!=''){echo $shippingAddress['region'].',';} ?><?php echo $shippingAddress['postcode']; ?></br>
					<?php echo $this->getCountryByCode($shippingAddress['country_id']); ?></br>
					<?php echo 'T: '.$shippingAddress['telephone']; ?>
				</address>
			</div>
		</div>
	<?php } ?>
		<div class="box box-order-shipping-address">
			<strong class="box-title">
				<span><?php echo __('Shipping Method') ?></span>
			</strong>
			<div class="box-content"><?php echo $orderCollection['shipping_description']; ?></div>
		</div>
		<div class="box box-order-billing-address">
			<strong class="box-title">
				<span><?php echo __('Billing Address') ?></span>
			</strong>
			<div class="box-content">
				<address>
					<?php echo $billingAddress['firstname']." "; ?><?php echo $billingAddress['lastname']; ?>
					<?php if($billingAddress['street']!=''){echo '</br>'.$billingAddress['street'];} ?></br>
					<?php echo $billingAddress['city'].", "; ?><?php if($billingAddress['region']!=''){echo $billingAddress['region'].',';} ?><?php echo $billingAddress['postcode']; ?></br>
					<?php echo $this->getCountryByCode($billingAddress['country_id']); ?></br>
					<?php echo 'T: '.$billingAddress['telephone']; ?></br>
				</address>
			</div>
		</div>
		<div class="box box-order-billing-method">
			<strong class="box-title">
				<span><?php echo __('Payment Method') ?></span>
			</strong>
			<div class="box-content">
				<dl class="payment-method checkmemo">
					<dt class="title"><?php echo $paymentMethod; ?></dt>
				</dl>
			</div>
		</div>
	</div>
</div>
<div class="block block-order-history">
    <div class="block-title">
        <strong><?= __('Order Comments') ?></strong>
    </div>
    <div class="block-content">
        <ul class="note-list">
            <?php foreach ($block->getStatusHistoryCollection() as $_item) : ?>
                <li class="note-list-item">
                    <span class="note-list-date"><?php echo date('d',strtotime($_item->getCreatedAt())).' '.__('of').' '.__(date("F",strtotime($_item->getCreatedAt()))).' '.__('of').' '.date("Y",strtotime($_item->getCreatedAt())).' '.__('at')?></span>
                    <span class="note-list-time"><?= /* @noEscape */ $block->formatTime($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
                    <span class="note-list-status">, <?= $block->escapeHtml($_item->getStatusLabel()) ?></span>
                    <span class="note-list-customer">
                        <?= $block->escapeHtml(__('Customer')) ?>
                        <?php if ($block->isCustomerNotificationNotApplicable($_item)) : ?>
                            <span class="note-list-customer-notapplicable">, <?= $block->escapeHtml(__('Notification Not Applicable')) ?></span>
                        <?php elseif ($_item->getIsCustomerNotified()) : ?>
                            <span class="note-list-customer-notified">, <?= $block->escapeHtml(__('Notified')) ?></span>
                        <?php else : ?>
                            <span class="note-list-customer-not-notified">, <?= $block->escapeHtml(__('Not Notified')) ?></span>
                        <?php endif; ?>
                    </span>
                    <?php if ($_item->getComment()) : ?>
                        <div class="note-list-comment"><?= $block->escapeHtml($_item->getComment(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?></div>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<div class="block block-order-communication">
    <div class="block-title">
        <strong><?= __('Communication with the customer') ?></strong>
    </div>
    <div class="block-content">
        <ul class="note-list">
            <?php $messageFlag = false; ?>
            <?php foreach ($block->getStatusMessagesCollection() as $_item) : ?>
                <?php $messageFlag = true; ?>
                <li class="note-list-item">
                    <span class="note-list-date"><?php echo date('d',strtotime($_item->getCreatedAt())).' '.__('of').' '.__(date("F",strtotime($_item->getCreatedAt()))).' '.__('of').' '.date("Y",strtotime($_item->getCreatedAt())).' '.__('at')?></span>
                    <span class="note-list-time"><?= /* @noEscape */ $block->formatTime($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?>,</span>
                    <span class="note-list-customer">
                        <?php if ($_item->getSmCustomerMessage() == 1) : ?>
                            <?= $block->escapeHtml(__('Sent by') . ' ' . __('Customer')) ?>
                        <?php else: ?>
                            <?= $block->escapeHtml(__('Sent by') . ' ' . __('Seller')) ?>
                        <?php endif; ?>
                        <span class="note-list-customer-notified">, <?= $block->escapeHtml(__('Notified')) ?></span>
                    </span>
                    <?php if ($_item->getComment()) : ?>
                        <div class="note-list-comment"><?= $block->escapeHtml($_item->getComment(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?></div>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
            <?php if (!$messageFlag) : ?>
                <li class="note-list-item"><div class="note-list-comment"><?= __('There are no direct communication messages with the client'); ?></div></li>
            <?php endif; ?>
        </ul>
        <form style="margin-top:20px;"class="form order-message" action="<?php echo $this->getUrl('sellerinfo/index/addMessageToCustomer', ['order_id' => $orderCollection['entity_id']]); ?>" id="order-message-form" method="post" enctype="multipart/form-data">
            <?php echo $this->getBlockHtml('formkey')?>
            <fieldset class="fieldset" style="margin-bottom:15px;">
                <div class="fields">
                    <div class="field seller_order_comment required">
                        <label for="history_comment" class="admin__field-label">
                            <?= $block->escapeHtml(__('Enviar nova mensagem ao cliente') ) ?>
                        </label>
                        <div class="admin__field-control">
                             <textarea name="history[comment]"
                              rows="3"
                              cols="5"
                              id="history_comment"
                              class="admin__control-textarea"></textarea>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary pts-review-box">
                    <button type="submit" title="Submit" class="action submit primary pts-newbtn-next">
                        <span><?= __('Save') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<?php echo $block->getChildHtml('stm_authorize_cancel'); ?>
