<!--
/**
* Purpletree_Marketplace storeview
* NOTICE OF LICENSE
*
* This source file is subject to the Purpletree License that is bundled with this package in the file license.txt.
* It is also available through online at this URL: https://www.purpletreesoftware.com/license.html
*
* @category    Purpletree
* @package     Purpletree_Marketplace
* @author      Purpletree Infotech Private Limited
* @copyright   Copyright (c) 2017
* @license     https://www.purpletreesoftware.com/license.html
*/
-->

<?php
	$storeData=$this->getStoreDetails();

	$getDataHelper = $this->getDataHelper();
	$values = array();
	if($getDataHelper != '') {
		$values = explode(',',$getDataHelper);
	}
	$imageUrl=$this->getImageUrl();
	$custId=$this->getSellerId();
	  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $customerObj = $objectManager->create('Magento\Customer\Model\Customer')->load($custId);
                        $customerEmail = $customerObj->getEmail();
	$reviewsavg=$this->getReviewsAvg();
	$isReviewVisible=$this->getReviewsVisible();
?>
<div class="pts-container_left">
	<div class="pts-left">
		<?php if($storeData['store_logo']!=''){?>
			<img class="pts-store-logo" src="<?php echo $imageUrl.$storeData['store_logo'];?>">

		<?php } else {?>
			<img class="pts-store-logo" src="<?php echo $this->getViewFileUrl('Purpletree_Marketplace::images/small_image.jpg'); ?>">
     <br>
		<?php }?>

		<?php if($isReviewVisible){?>
            <div class="container-pts-rating-box">
            <!--    <h3 class="text">Avaliação da loja</h3>
                <div class="pts-rating-box">
                    <div class="pts-rating" style="width:< ?php echo $reviewsavg * 20; ?>%;"></div>
                </div>
                <h3 class="text">Avaliações dos pedidos</h3>-->
                <div class="pts-rating-box">
                    <div class="pts-rating" style="width:<?php echo $reviewsavg * 20; ?>%;"></div>
                </div>
            </div>

            <div class="content-review-link">
                <p><a target="_blank" class="product-item-link"> <?php echo __('Store Review');?> <?php echo ' ('.$this->getReviewsCount().')';?></a><br></p>
            </div>
          <!--  <p><a target="_blank" class="product-item-link" href="<?php echo $this->getUrl('*/*/sellerreview').'sellerid/'.$storeData['seller_id']; ?>"> <?php echo __('Store Review');?> <?php echo ' ('.$this->getReviewsCount().')';?></a><br></p> -->
		<?php } ?>
		<p>
		<div class="hline">
			<!-- < ?php if(in_array('email',$values)): ?>
			<b>< ?php echo __('Store Email Id');?></b>< ?php echo ' : '.$customerEmail;?><br>
			< ?php endif; ?>
			< ?php if(in_array('phone',$values)): ?>
			<b>< ?php echo __('Store Contact Number');?></b>< ?php echo ' : '.$storeData['store_phone'];?><br>
			< ?php endif; ?> -->
			<?php if(in_array('address',$values)): ?>
			<b><?php echo __('Localização da loja:');?></b>
			<br><?php echo $storeData['store_city'];?></b><?php echo ', ';
			if($storeData['store_region_id']==0){echo $storeData['store_region'];}else{echo $this->getStateByCode($storeData['store_region_id']);}?>
			<br><?php echo $this->getCountryByCode($storeData['store_country']);?>
			<?php endif; ?>
 	</div>
	<!--<div class="space-line-hline"></div>
		<p><a target="_blank" class="product-item-link" href="<?php echo $this->getUrl('*/*/shippingpolicy').'sellerid/'.$storeData['seller_id'];?>"> <?php echo __('Store Shipping Policy');?> </a><br></p>
		<p><a target="_blank" class="product-item-link" href="<?php echo $this->getUrl('*/*/returnpolicy').'sellerid/'.$storeData['seller_id'];?>"> <?php echo __('Store Return Policy');?> </a><br></p>
	</div>-->
        <?php
        echo $this->getLayout()
            ->createBlock('Softtek\RemoveDescription\Block\RemoveDescription')
            ->setTemplate('Softtek_RemoveDescription::policy.phtml')
            ->toHtml();
        ?>
</div>
<style>
.toolbar.toolbar-products {
	margin-top:15px;
}
.toolbar.toolbar-products .field.limiter {
	display: inline-block;
}
.products-grid .product-item-inner {
	margin-top:9px;
}
</style>
