<?php
/**
 * @package     Plumrocket_DataPrivacy
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Plumrocket\DataPrivacy\ViewModel\Dashboard\DataProtectionOfficer $viewModel */
$viewModel = $block->getData('viewModel');
?>

<?php if ($viewModel->canShow()): ?>
    <li class="prgdpr__item">
        <a class="prgdpr__link" href="mailto:<?= /* @noEscape */ $viewModel->getEmail() ?>">
            <svg class="prgdpr__icon" width="70" height="70">
                <use xlink:href="#<?= /* @noEscape */ $block->getData('icon') ?>"></use>
            </svg>
            <b class="prgdpr__name"><?= $block->escapeHtml($block->getData('label')) ?></b>
            <p class="prgdpr__text"><?= $block->escapeHtml($block->getData('description')) ?></p>
        </a>
    </li>
<?php endif; ?>
