<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php
    $_product = $block->getProduct();
?>

<?php if ($_product->getWeight()): ?>
    <div class="product-weight"><?= $block->escapeHtml(__('Embalagem de')) ?>&nbsp;<?php echo floatval($_product->getWeight()); ?>&nbsp;kg</div>
<?php endif ?>
