<?php
/**
 *
 * Edit customer address template
 *
 *
 * NOTICE OF LICENSE
 *
 * @category   Softtek
 * @package    Softtek_CheckoutBR
 * @author     www.sofftek.com
 * @copyright  Softtek Brasil
 * @license    http://opensource.org/licenses/osl-3.0.php
 */
?>
<?php
/**
 * @var $block \Magento\Customer\Block\Address\Edit
 */
?>
<?php $customer = $block->getData("customer_view_model")->getCurrentCustomer(); ?>
<form class="form-address-edit" data-mage-init='{"validation": {}}' action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" id="form-validate" novalidate="novalidate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span></legend><br>
        <?php echo $block->getBlockHtml('formkey')?>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
        <?php echo $block->getNameBlockHtml() ?>
        <div class="field telephone required">
            <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
            <div class="control">
                <input type="text" id="telephone" name="telephone" value="<?php echo $block->escapeHtml($block->getAddress()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
            </div>
        </div>
        <!-- <div class="field fax">
            <label class="label" for="fax"><span>< ?php /* @escapeNotVerified */ echo __('Fax') ?></span></label>
            <div class="control">
                <input type="text" name="fax" id="fax" title="< ?php /* @escapeNotVerified */ echo __('Fax') ?>" value="< ?php echo $block->escapeHtml($block->getAddress()->getFax()) ?>" class="input-text < ?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('fax') ?>">
            </div>
        </div>
        <div class="field company">
            <label class="label" for="company"><span>< ?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
            <div class="control">
                <input type="text" name="company" id="company" title="< ?php /* @escapeNotVerified */ echo __('Company') ?>" value="< ?php echo $block->escapeHtml($block->getAddress()->getCompany()) ?>" class="input-text < ?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
            </div>
        </div> -->
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></legend><br>

        <div class="field zip required">
            <label class="label" for="zip"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
            <div class="control">
                <input type="text"
                aria-required="true"
                id="postcode" name="postcode" value="<?php echo $block->escapeHtml($block->getAddress()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="required-entry input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?> required-entry">
            </div>
        </div>


        <?php echo $block->getLayout()->createBlock('Softtek\CheckoutBR\Block\Magento\Customer\Widget\StreetprefixEdit')->toHtml() ?>

        <?php echo $block->getLayout()->createBlock('Softtek\CheckoutBR\Block\Magento\Customer\Widget\Streetedit')->toHtml() ?>

        <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id"><span><?php /* @escapeNotVerified */ echo __('VAT Number') ?></span></label>
                <div class="control">
                    <input type="text" name="vat_id" value="<?php echo $block->escapeHtml($block->getAddress()->getVatId()) ?>" title="<?php /* @escapeNotVerified */ echo __('VAT Number') ?>" id="vat_id" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id') ?>">
                </div>
            </div>
        <?php endif; ?>
        <div class="field city required">
            <label class="label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
            <div class="control">
                <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getAddress()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>"  id="city" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>">
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
            <div class="control">
                <select id="region_id" name="region_id" required title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="required-entry validate-select" <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>"  title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?> style="display: none;" />
                <input type="hidden" id="region_id_aux" name="region" value="<?php echo $block->escapeHtml($block->getRegionId()) ?>"  title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?> style="display: none;"/>
            </div>
        </div>

        <div class="field country required">
            <label class="label" for="country"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
            <div class="control">
                <?php echo $block->getCountryHtmlSelect() ?>
            </div>
        </div>

        <?php if ($customer->getIsSeller()): ?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        <?php else: ?>
            <?php if ($block->isDefaultBilling()): ?>
                <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default billing address.") ?></div>
                <input type="hidden" name="default_billing" value="1" />
            <?php elseif ($block->canSetAsDefaultBilling()): ?>
                <div class="field choice set billing">
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                    <label class="label" for="primary_billing"><span><?php /* @escapeNotVerified */ echo __('Use as my default billing address') ?></span></label>
                </div>
            <?php //else: ?>
                <!-- <input type="hidden" name="default_billing" value="1" /> -->
            <?php endif; ?>

            <?php if ($block->isDefaultShipping()): ?>
                <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default shipping address.") ?></div>
                <input type="hidden" name="default_shipping" value="1">
            <?php elseif ($block->canSetAsDefaultShipping()): ?>
                <div class="field choice set shipping">
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                    <label class="label" for="primary_shipping"><span><?php /* @escapeNotVerified */ echo __('Use as my default shipping address') ?></span></label>
                </div>
            <?php //else: ?>
               <input type="hidden" name="default_shipping" value="1">
            <?php endif; ?>
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save Address') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
<?php if ($block->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery','mage/mage'], function($) {
        $(document).ready(function($) {
            //$( "#countryselect" ).change(function(event) {
            $('#country').on('change', function() {
                var country_id =$(this).val();
                $('[data-role="pannel"]').trigger('show.loader');
                $.ajax({
                    type 	 : "POST",
                    url 	 : "<?php echo $this->getUrl('sellerinfo/index/getstate'); ?>",
                    data: "country_id="+country_id ,
                    showLoader: true,
                    dataType: "json",
                    success: function( data ){
                        $('#region_id').empty();
                        $.each(data,function(k1,v1){
                            if(v1.status == 'true') {
                                $('#region').css('display','none');
                                $('#region_id').css('display','block');
                                $('#region').val('');
                            }
                            if(v1.status == 'false') {
                                $('#region').css('display','block');
                                $('#region_id').css('display','none');
                                $('#region').val('');
                            }
                            var region = $('#region_id_aux').val();
                            if($.isArray(v1)) {
                                $.each(v1,function(k,v){
                                    if(v.value == region){
                                        $('#region_id').append('<option id="stat'+ v.value +'" value="'+ v.value +'" selected>'+ v.label +'</option>');
                                    }else{
                                        $('#region_id').append('<option id="stat'+ v.value +'" value="'+ v.value +'">'+ v.label +'</option>');
                                    }
                                });
                            }
                        });
                        $('[data-role="pannel"]').trigger('hide.loader');
                    },
                    error: function(){
                        alert('something went wrong');
                    }
                });
            });
            $('#region_id').on('change', function() {
                $('#region_name').val($("#region_id option:selected").text());
            });
            setTimeout(function(){
                $('#country').trigger('change');
            }, 2000);
            $('#country').css('pointer-events', 'none');
            $('#country').css('background-color', '#f3f3f3');
        });
    });
</script>
<script type="text/javascript">
require([
    'jquery',
    'inputMask',
    'mage/url',
    'loader'
], function ($, mask, url) {
    $("#postcode").mask('00000-000', {clearIfNotMatch: true});
    $('#postcode').on('change', function(){
        var zipcode = $(this).val().replace('-', '');
        var ajaxurl = url.build('rest/V1/magedev-brazil-zipcode/search/' + zipcode);
        $('body').loader('show');

        $.ajax({
            url: ajaxurl,
            dataType: 'json',
            timeout: 4000,
            async: true
        }).done(function (data) {
            if(data.error){
                // TODO
            }else{
                $("#street_1").val(data.street??'');
                $("#street_3").val(data.neighborhood??'');
                $("#street_4").val(data.additional_info??'');
                $("#city").val(data.city??'');
                $("#country").val('BR');
                $("#region_id").val(data.region_id??'');
            }
        }).error(function(){});

        $('body').loader('hide');
    });

    var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
            },
            clearIfNotMatch: true
        };

    $('#telephone').mask(SPMaskBehavior, spOptions);
    $('#fax').mask(SPMaskBehavior, spOptions);
});
</script>
