<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_CookieConsent
 * @copyright   Copyright (c) 2021 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

/** @var \Plumrocket\CookieConsent\Block\Widget\CookieSettingsButton $block */
?>

<a href="#" class="pr-open-cookie-settings" title="<?= $block->escapeHtmlAttr(__($block->getTitle())) ?>">
    <?= $block->escapeHtml(__($block->getTitle())) ?>
</a>
