<!--
/**
* Purpletree_Marketplace scriptjs
* NOTICE OF LICENSE
*
* This source file is subject to the Purpletree License that is bundled with this package in the file license.txt.
* It is also available through online at this URL: https://www.purpletreesoftware.com/license.html
*
* @category    Purpletree
* @package     Purpletree_Marketplace
* @author      Purpletree Infotech Private Limited
* @copyright   Copyright (c) 2017
* @license     https://www.purpletreesoftware.com/license.html
*/
-->
<script>
    require([
        "jquery",

    ], function($){     

        $("input[name='product_ids']").attr('data-form-part','customer_form');      
    });
</script>