
<div class="field tcagreecreateaccount required">
    <div class="control">
        <input type="checkbox" id="tcagreecreateaccount" name="tcagreecreateaccount" data-validate="{required:true}" class="input-checkbox checkbox required" value="1">
        <label for="tcagreecreateaccount" class="label">
            <?php $_link ="/privacy-policy-cookie-restriction-mode" ?>
            <?= __('Não se preocupe, nosso site é seguro! Ao criar o seu cadastro, você concorda com a nossa <a href="%1" target="_blank">Política de Privacidade.</a>  <span style="color: red;">*</span>',$_link) ?>
        </label>
        <div class="msg-alert password-strength-meter"><?= __('Você precisa concordar com nossa Política de Privacidade.') ?></div>
    </div>
</div>
