<?php
/**
 *
 * Person type fields template
 *
 *
 * NOTICE OF LICENSE
 *
 * @category   Softtek
 * @package    Softtek_CheckoutBR
 * @author     www.sofftek.com
 * @copyright  Softtek Brasil
 * @license    http://opensource.org/licenses/osl-3.0.php
 */
?>
<?php if($block->showCpf): ?>
    <div class="field fieldset individual" data-container="type-individual">
        <?php if($block->getStatus("show", "cpf", "cpf")): ?>
            <div class="field<?php echo ($block->getStatus("required", "cpf", "cpf")?" required":"") ?>">
                <label for="cpf" class="label"><span><?php /* @escapeNotVerified */ echo __('CPF') ?></span></label>
                <div class="control">
                    <input type="text"
                           id="cpf"
                           name="cpf"
                           value="<?php echo $block->escapeHtml($block->getCustomerValue("cpf")) ?>"
                           title="<?php /* @escapeNotVerified */ echo __('CPF') ?>"
                           class="input-text"
                           data-validate="{required:<?php echo var_export($block->getStatus("required", "cpf", "cpf"), true) ?>, 'validate-cpf':true}">
                </div>
            </div>
        <?php endif; ?>

        <?php if($block->getStatus("show", "cpf", "rg")): ?>
            <div class="field<?php echo ($block->getStatus("required", "cpf", "rg")?" required":"") ?>">
                <label for="rg" class="label"><span><?php /* @escapeNotVerified */ echo __('RG') ?></span></label>
                <div class="control">
                    <input type="text"
                           id="rg"
                           name="rg"
                           value="<?php echo $block->escapeHtml($block->getCustomerValue("rg")) ?>"
                           title="<?php /* @escapeNotVerified */ echo __('RG') ?>"
                           class="input-text"
                           data-validate="{required:<?php echo var_export($block->getStatus("required", "cpf", "rg"), true) ?>}" >
                </div>
            </div>
        <?php endif; ?>

    </div>
<?php endif; ?>

<?php if($block->showCnpj): ?>

<?php endif; ?>

<script type="text/x-magento-init">
    {
        "[data-role=type-individual], [data-role=type-corporation]": {
            "changePersonType" : {
                "changeFirstnameLabel": <?php echo ($block->getConfigAdmin("cnpj", "copy_firstname")?"true":"false"); ?>,
                "changeLastnameLabel": <?php echo ($block->getConfigAdmin("cnpj", "copy_lastname")?"true":"false"); ?>
            }
        },
        "#cnpj": {
            "cnpjUpdater": {}
        }
    }
</script>

<script>
  var SPMaskBehavior = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
    },
    spOptions = {
        onKeyPress: function(val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
        },
        clearIfNotMatch: true
    };
    require([
        'jquery',
        'inputMask'
    ], function ($) {
        $('#cpf').mask('000.000.000-00', {clearIfNotMatch: true});
        $('#cnpj').mask('00.000.000/0000-00', {clearIfNotMatch: false});
        $('#ie').mask('000.000.000.000', {clearIfNotMatch: false});
        $('#telephone').mask(SPMaskBehavior, spOptions);
    });
</script>
