<!--
/**
* Purpletree_Marketplace becomeseller
* NOTICE OF LICENSE
*
* This source file is subject to the Purpletree License that is bundled with this package in the file license.txt.
* It is also available through online at this URL: https://www.purpletreesoftware.com/license.html
*
* @category    Purpletree
* @package     Purpletree_Marketplace
* @author      Purpletree Infotech Private Limited
* @copyright   Copyright (c) 2017
* @license     https://www.purpletreesoftware.com/license.html
*/
-->
<?php
	$storeData=$this->getStoreDetails();
	$isSeller=$this->getIsSeller();
?>
<form class="form becomeseller" data-mage-init='{"validation": {}}' action="<?php echo $this->getUrl('sellerinfo/index/sellersave') ?>" id="becomeseller-form" method="post" data-hasrequired="* Required Fields" novalidate="novalidate" enctype="multipart/form-data" >
	<?php echo $this->getBlockHtml('formkey')?>
    <fieldset class="fieldset" >
        <div class="fields">
        <?php if ($isSeller == 1 && $storeData['status_id'] != 4) { ?>
            <div class="field store-url-ctn required">
                <label class="label" for="store-url">
                    <span><?= $block->escapeHtml(__('Store Url')) ?></span>
                </label>
                <div class="control">
                    <input type="hidden" name="ut" value="seller" />
                    <input type="text" id="store-url" class="store-url validate-code input-text" name="store_url" data-validate="{'required':true}" value="<?= $storeData['store_url'] ?? '' ?>"/>
                    <p style="font-size: 11px;padding-top: 3px;"><?= __('Enter Unique Alphanumeric Storeurl to be used as your URL.') ?></p>
                    <div class="errormsg"  style=" color: #e02b27;font-size: 12px;"></div>
                </div>
            </div>
            <!-- START -->
            <div class="field storename required">
                <label class="label" for="store_name"><span><?php echo __('Store Name');?></span></label>
                <div class="control">
                    <input name="store_name" id="store_name" title="Store Name" value="<?= $storeData['store_name'] ?? '' ?>" class="input-text" required type="text" data-validate="{required:true}">
                </div>
            </div>
            <div class="field storephone required">
                <label class="label" for="store_phone"><span><?php echo __('Store Phone Number');?></span></label>
                <div class="control">
                    <input name="store_phone" id="store_phone" title="storephone" value="<?= $storeData['store_phone'] ?? '' ?>" class="input-text" required type="text" data-validate="{required:true}">
                </div>
            </div>
            <div class="field storetin">
                <label class="label" for="store_tin_number"><span><?php echo __('Store Tax Identification Number');?></span></label>
                <div class="control">
                    <input name="store_tin_number" id="store_tin_number" title="storetin" value="<?= $storeData['store_tin_number'] ?? '' ?>" class="input-text" type="text" data-validate="{'validate-number':true}">
                </div>
            </div>
            <div class="field storeaccount" style="display: none;">
                <label class="label" for="store_bank_account"><span><?php echo __('Store Bank Details');?></span></label>
                <div class="control">
                    <textarea name="store_bank_account" id="store_bank_account" title="storeaccount" class="input-text" type="text" rows="3" ><?= $storeData['store_bank_account'] ?? '' ?></textarea>
                </div>
            </div>
            <div class="field storeaddress required">
                <label class="label" for="store_address"><span><?php echo __('Store Address');?></span></label>
                <div class="control">
                    <textarea name="store_address" id="store_address" title="store address" class="input-text" rows="3" data-validate="{required:true}" ><?= $storeData['store_address'] ?? '' ?></textarea>
                </div>
            </div>
            <div class="field countryselect required">
                <label class="label" for="countryselect"><span><?php echo __('Store Country');?></span></label>
                <div class="control">
                    <select name="store_country" style="pointer-events: none;background-color: #f3f3f3;" class="" id="countryselect" title="manufacture" data-validate="{required:true}">
                        <?php  foreach($this->getCountry() as $country) { ?>
                            <option value="<?php echo $country['value'] ?>" <?php if(isset($storeData['store_country']) && $country['value']==$storeData['store_country']){echo 'selected';} ?>><?php echo $country['label']; ?></option>
                        <?php }  ?>
                    </select>
                </div>
            </div>
            <div class="field state required">
                <label class="label" for="state"><span><?php echo __('Store State/Province');?></span></label>
                <div class="control">
                    <input <?php  echo (isset($storeData['store_region_id']) && $storeData['store_region_id'] == 0) ? 'style="display:block"':'style="display:none"'; ?> value="<?= $storeData['store_region'] ?? '' ?>" type="text" name="store_region" id="region_name" data-validate="{required:true}" />

                    <select <?php  echo ($storeData['store_region_id'] ?? 0) != 0 ? 'style="display:block"':'style="display:none"'; ?> class="select" name="store_region" id="region_id" data-validate="{required:true}">
                        <?php $stateArrayData= (isset($storeData['store_country'])) ? $this->getRegionByCountry($storeData['store_country']) : [];
                        foreach($stateArrayData as $stateArray) { ?>

                            <option value="<?php echo $stateArray['value'] ?>" <?php if(isset($storeData['store_region_id']) && $stateArray['value']==$storeData['store_region_id']){echo 'selected';} ?> ><?php echo $stateArray['label']; ?></option>

                        <?php }  ?>
                    </select>
                </div>
            </div>
            <div class="field storecity required">
                <label class="label" for="store_city"><span><?php echo __('Store City');?></span></label>
                <div class="control">
                    <input  type="text" name="store_city" value="<?= $storeData['store_city'] ?? '' ?>" id="store_city" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field storezip required">
                <label class="label" for="store_zipcode"><span><?php echo __('Store Zipcode');?></span></label>
                <div class="control">
                    <input type="text" value="<?= $storeData['store_zipcode'] ?? '' ?>" name="store_zipcode" id="postcode" class="input-text validate-zip-international  required-entry" required data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field storedescription required">
                <label class="label" for="store_description"><span><?php echo __('Store Description');?></span></label>
                <div class="control">
                    <textarea name="store_description" id="store_description" title="Description" class="input-text" rows="3" data-validate="{required:true}" ><?= $storeData['store_description'] ?? '' ?></textarea>
                    <span class="error" style="color: #a80000;font-weight: bold;"></span>
                    <div class="mage-error description-error" generated="true"></div>
                </div>
            </div>
            <div class="field shippingpolicy">
                <label class="label" for="store_shipping_policy"><span><?php echo __('Store Shipping Policy');?></span></label>
                <div class="control">
                    <textarea name="store_shipping_policy" id="store_shipping_policy" title="shippingpolicy" class="input-text" rows="3"><?= $storeData['store_shipping_policy'] ?? '' ?></textarea>
                </div>
            </div>
            <div class="field returnpolicy">
                <label class="label" for="store_return_policy"><span><?php echo __('Store Return Policy');?></span></label>
                <div class="control">
                    <textarea name="store_return_policy" id="store_return_policy" title="returnpolicy" class="input-text" rows="3"><?= $storeData['store_return_policy'] ?? '' ?></textarea>
                </div>
            </div>
            <div class="field keywords">
                <label class="label" for="store_meta_keywords"><span><?php echo __('Store Meta Keywords');?></span></label>
                <div class="control">
                    <textarea name="store_meta_keywords" id="store_meta_keywords" title="Keywords" class="input-text" rows="3"><?= $storeData['store_meta_keywords'] ?? '' ?></textarea>
                </div>
            </div>
            <div class="field metadescription">
                <label class="label" for="store_meta_descriptions"><span><?php echo __('Store Meta Description');?></span></label>
                <div class="control control">
                    <textarea name="store_meta_descriptions" id="store_meta_descriptions" title="Description" class="input-text" rows="3"><?= $storeData['store_meta_descriptions'] ?? '' ?></textarea>
                </div>
            </div>
            <div class="field keywords">
                <label class="label" for="keywords"><span><?php echo __('Store Logo');?></span></label>
                <div class="control">
                    <p>
                        <input name="logo" id="logo" title="Logo" class="input-text" type="file">
                    </p>
                    <?php if($storeData['store_logo'] ?? ''){?>
                        <p>
                            <img class="pts-store-logo" src="<?php echo $imageUrl . $storeData['store_logo'];?>" height="150px" width="150px;">
                        </p>
                    <?php }?>
                    <input name="store_old_logo" id="store_old_logo" value="<?= $storeData['store_logo'] ?? '' ?>" type="hidden">
                    <p style="font-size: 10px;"><?php echo __('Recomended Dimensions are 200 X 200');?></p>
                </div>
            </div>
            <div class="field description">
                <label class="label" for="metadescription"><span><?php echo __('Store Banner');?></span></label>
                <div class="control">
                    <p>
                        <input name="banner" id="banner" title="banner" class="input-text" type="file">
                    </p>
                    <?php if($storeData['store_banner'] ?? ''){?>
                        <p>
                            <img class="pts-store-logo" src="<?php echo $imageUrl.$storeData['store_banner'];?>" height="300px" width="300px;">
                        </p>
                    <?php }?>

                    <input name="store_old_banner" id="store_old_banner" value="<?= $storeData['store_banner'] ?? '' ?>" type="hidden">
                    <p style="font-size: 10px;"><?php echo __('Recomended Dimensions are 900 X 300(W X H)');?></p>
                </div>
            </div>
            <!-- END -->
        <?php
            } elseif (isset($storeData['status_id']) && $storeData['status_id'] == 4 && $isSeller == 1) { ?>
                <div class="pts-waitingmsg">
                    <div class="pts-waitingmsg-block">
                        <label name="seller_label" class="label"><span><?php echo __('Waiting for admin for data approval') ?></span></label><br>
                    </div>
                </div>
                <style>
                .pts-seller-submit {
                    display:none !important;
                }
                </style>
        <?php
            }
        ?>
            <input name="status_id" id="status_id" value="<?= (int)$storeData['status_id'] ?? '' ?>" type="hidden">
            <input name="again_seller" id="again_seller" value="0" type="hidden">
            <input name="seller_id" id="seller_id" value="<?= $storeData['seller_id'] ?? '' ?>" type="hidden">
            <input name="entity_idpts" id="entity_idpts" value="<?= $storeData['entity_idpts'] ?? '' ?>" type="hidden">
        </div>
    </fieldset>
    <?php if ($isSeller == 1 && $storeData['status_id'] != 4) { ?>
        <div class="actions-toolbar">
            <div class="primary">
                <input name="hideit" id="hideit" value="" type="hidden">
                <button type="submit" title="Submit" id="sellersubmit" class="action submit primary pts-seller-submit pts-newbtn-next">
                    <span><?php echo __('Submit'); ?></span>
                </button>
            </div>
        </div>
	<?php } ?>
</form>
<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui'
    ], function($) {
        $(document).ready(function() {
            var pageTitle = $('.page-title-wrapper .page-title span');
            if (pageTitle.length > 0) {
                <?php if ($storeData['status_id'] == 3) { ?>
                    pageTitle.html('<?= __('Create new seller account') ?>');
                <?php } else { ?>
                    pageTitle.html('<?= __('Become Seller') ?>');
                <?php } ?>
                $('.page-title-wrapper').show('blind', {}, 500);
            }
            $('#store-url').on('blur', function() {
                var storeurl = $("#store-url").val();
                if (storeurl == '') {
                    return;
                }
                $.ajax({
                    url: "<?php echo $this->getUrl('marketplace/index/sellerunique'); ?>",
                    dataType: 'json',
                    showLoader: true,
                    data: 'store_url=' + storeurl,
                    type: 'POST',
                    success: function (result) {
                        if (result != 0) {
                            $('.errormsg').css('display', 'block');
                            $('.errormsg').html('<span><?php echo __("Enter Unique Store URL"); ?></span>');
                            $('#sellersubmit').prop('disabled', true);
                        } else {
                            $('.errormsg').css('display', 'none');
                            $('#sellersubmit').prop('disabled', false);
                        }
                    }
                });
            });

            $(document).on('click', '#sellersubmit', function() {
                var dataForm = $('#becomeseller-form');
                var resultFormValidation = dataForm.validation('isValid');
                if (resultFormValidation) {
                    var msg = $('#store_description').val();
                    var textMsg = $.trim($(msg).text());
                    if (textMsg == '') {
                        $('.description-error').show();
                        $('.description-error').html('<?php echo __("This is a required field."); ?>');
                        $([document.documentElement, document.body]).animate({
                            scrollTop: $("#postcode").offset().top
                        }, 2000);
                        return false;
                    } else {
                        $('.description-error').hide();
                        $('.description-error').html('');
                    }
                }
            });

            <?php if (isset($storeData['tcagreecreateaccount'])) { ?>
                $('#tcagreecreateaccount').prop('checked', true);
            <?php } ?>
            var currentRegionId = 0;
            <?php if (isset($storeData['store_region'])) { ?>
                currentRegionId = <?php echo (int)$storeData['store_region']; ?>;
                setTimeout(function() {
                    $('#region_id option[value="<?php echo $storeData['store_region']; ?>"]').attr('selected', true);
                }, 2000);
            <?php } ?>
        });
    });
</script>
<script type="text/javascript">
    require([
        'jquery',
        'inputMask',
        'mage/url',
        'loader'
    ], function ($, mask, url) {
        $("#postcode").mask('00000-000', {clearIfNotMatch: true});
        $('#postcode').on('change', function(){
            var zipcode = $(this).val().replace('-', '');
            var ajaxurl = url.build('rest/V1/magedev-brazil-zipcode/search/' + zipcode);
            $('body').loader('show');

            $.ajax({
                url: ajaxurl,
                dataType: 'json',
                timeout: 4000,
                async: true
            }).done(function (data) {
                if(data.error){
                    // TODO
                }else{
                    $("#street_1").val(data.street??'');
                    $("#street_3").val(data.neighborhood??'');
                    $("#street_4").val(data.additional_info??'');
                    $("#city").val(data.city??'');
                    $("#country").val('BR');
                    $("#region_id").val(data.region_id??'');
                }
            }).error(function(){});

            $('body').loader('hide');
        });

        var SPMaskBehavior = function (val) {
                return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
            },
            spOptions = {
                onKeyPress: function(val, e, field, options) {
                    field.mask(SPMaskBehavior.apply({}, arguments), options);
                },
                clearIfNotMatch: true
            };

        $('#telephone').mask(SPMaskBehavior, spOptions);
        $('#store_phone').mask(SPMaskBehavior, spOptions);
        $('#fax').mask(SPMaskBehavior, spOptions);
    });

</script>
<script type="text/javascript">
    require(['jquery','mage/mage'], function($) {
        $(document).ready(function($) {
            //$( "#countryselect" ).change(function(event) {
            $('#countryselect').on('change', function() {
                var country_id =$(this).val();
                $('[data-role="pannel"]').trigger('show.loader');
                $.ajax({
                    type 	 : "POST",
                    url 	 : "<?php echo $this->getUrl('sellerinfo/index/getstate'); ?>",
                    data: "country_id="+country_id ,
                    showLoader: true,
                    dataType: "json",
                    success: function( data ){
                        $('#region_id').empty();
                        $.each(data,function(k1,v1){
                            if(v1.status == 'true') {
                                $('#region_name').css('display','none');
                                $('#region_id').css('display','block');
                                $('#region_name').val('');
                            }
                            if(v1.status == 'false') {
                                $('#region_name').css('display','block');
                                $('#region_id').css('display','none');
                                $('#region_name').val('');
                            }
                            if($.isArray(v1)) {
                                $.each(v1,function(k,v){
                                    $('#region_id').append('<option id="stat'+ v.value +'" value="'+ v.value +'">'+ v.label +'</option>');
                                    $('#region_name').val('');
                                });
                            }
                        });
                        $('[data-role="pannel"]').trigger('hide.loader');
                    },
                    error: function(){
                        alert('something went wrong');
                    }
                });
            });
            $('#region_id').on('change', function() {
                $('#region_name').val($("#region_id option:selected").text());
            });
            setTimeout(function(){
                $('#countryselect').trigger('change');
            }, 2000);
        });
    });
</script>
<?php if(version_compare($this->getVersion(),  "2.3.0") == -1) { ?>
    <script type="text/javascript">
        require(['jquery','mage/adminhtml/wysiwyg/tiny_mce/setup'], function($) {
            $(document).ready(function($) {
                tinyMCE.init({
                    mode : "exact",
                    elements: "store_description,store_shipping_policy,store_return_policy",
                    theme : "advanced",
                    plugins : "inlinepopups,style,layer,table,save,advhr,advlink,emotions,iespell,insertdatetime,preview,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
                    theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
                    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,cleanup,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
                    theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,advhr,|,print,|,ltr,rtl,|,fullscreen",
                    theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
                    theme_advanced_toolbar_location : "top",
                    theme_advanced_toolbar_align : "left",
                    theme_advanced_path_location : "bottom",
                    extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
                    theme_advanced_resize_horizontal : 'true',
                    theme_advanced_resizing : 'true',
                    apply_source_formatting : 'true',
                    convert_urls : 'false',
                    force_br_newlines : 'true',
                    doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'
                });
            });
        });
    </script>
<?php } else { ?>
    <script type="text/javascript">
        require(['jquery','mage/adminhtml/wysiwyg/tiny_mce/setup'], function($) {
            $(document).ready(function($) {
                tinyMCE.init({
                    mode : "exact",
                    elements: "store_description,store_shipping_policy,store_return_policy",
                    plugins: "image",
                    menubar: "",
                    toolbar: "image | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link | fontsizeselect forecolor backcolor | preview fullscreen | template | formatselect | fontselect |fontsizeselect",
                    removed_menuitems: 'newdocument',
                    extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
                    apply_source_formatting : 'true',
                    convert_urls : 'false',
                    force_br_newlines : 'true',
                    doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">',
                    setup: function (editor) {
                        editor.on('change', function () {
                            tinyMCE.triggerSave();
                        });
                    }
                });
            });
        });
    </script>
<?php } ?>
