<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_GDPR
 * @copyright   Copyright (c) 2018 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

// @codingStandardsIgnoreFile

use Plumrocket\GDPR\Helper\Checkboxes;

/**
 * @var $helper \Plumrocket\GDPR\Helper\Checkboxes
 */
$helper = $this->helper(Checkboxes::class);
$locationKey = $block->getData('locationKey');
$checkboxes = $helper->getCheckboxes($locationKey, true);

if (empty($checkboxes)) {
    return;
}
?>

<script>
    var consentCheckboxesConfig = <?= /* @noEscape */ $helper->serialize($checkboxes) ?>;
    var consentCheckboxesLocation = '<?= /* @noEscape */ $locationKey ?>';
</script>
