<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_GDPR
 * @copyright   Copyright (c) 2018 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>

<script type="text/x-magento-init">
{
    "*": {
        "Plumrocket_GDPR/js/load-consent-popups": {
            "loadUrl": "<?= $block->escapeUrl($block->getUrl('prgdpr/consentpopups/load')) ?>",
            "loadContainer": "#prgdpr-consentpopups-container"
        }
    }
}
</script>

<div id="prgdpr-consentpopups-container"></div>
