<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_GeoIPLookup
 * @copyright   Copyright (c) 2018 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php /** @var \Plumrocket\GeoIPLookup\Block\Adminhtml\System\Config\Data\Buttons\AbstractBlock $block */ ?>

<div class="pp-buttons-container">
    <button id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"
            onclick="<?= /* @noEscape */ $block->getOnclick($block->getHtmlId()) ?>">
        <span>
            <span>
                <span>
                    <?= $block->escapeHtml($block->getButtonLabel()) ?>
                </span>
            </span>
        </span>
    </button>
</div>
