<?php
/**
 * @category   Softtek
 * @package    Softtek_Marketplace
 * @author     yordan@softtek.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Softtek\Marketplace\Model;

use Magento\Framework\Model\AbstractModel;

class OrderReview extends AbstractModel
{
    /**
     * Define resource model
     */
    protected function _construct()
    {
        $this->_init('Softtek\Marketplace\Model\ResourceModel\OrderReview');
    }
}