<?php

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<style>
    .categoria-producto {
        color: #797979;
    }

    .marca-nombre {
        color: #7a4aab;
    }

    .filter-options-item {
        max-width: 15vw;
    }

    @media (min-width: 1024px) {
        .products.list.items.product-items .item.product.product-item {
            margin: 0;
            width: 22% !important;
            padding: 0.5rem !important;
            margin: 0.7rem;
        }
    }

    @media (max-width: 540px),
    print {
        layer-product-list {
            padding-left: 0rem !important;
            padding-right: 0rem !important;
            margin: 0.5rem !important;
        }
    }

    @media (max-width: 560px) {
        .products.list.items.product-items .item.product.product-item {
            width: 46% !important;
            height: 42rem;
        }
    }

    @media (max-width: 500px) {
        .products.list.items.product-items .item.product.product-item {
            width: 46% !important;
            height: 39rem;
        }

        .items {
            padding-left: 0rem !important;
            padding-right: 0rem !important;
        }

        #layer-product-list {
            padding-left: 0rem !important;
            padding-right: 0rem !important;
        }
    }

    @media (max-width: 767px) {
        .products.list.items.product-items .item.product.product-item {
            width: 40%;
            margin: 0.5rem;
            box-shadow: 4px 10px 13px 0 rgba(0, 0, 0, 0.11);
            background-color: #ffffff;
            margin-bottom: 1.5rem;
        }

        .filter-options-item {
            max-width: 100%;
        }

        .filter.active .filter-options {
            top: 8vh;
        }

        .fixed-top {
            position: initial !important;
            top: 15rem;
        }
    }

    @media (min-width: 768px),
    print {
        .page-products .products-grid .product-item {
            -webkit-box-shadow: 4px 10px 13px 0 rgba(0, 0, 0, 0.11);
            -moz-box-shadow: 4px 10px 13px 0 rgba(0, 0, 0, 0.11);
            box-shadow: 4px 10px 13px 0 rgba(0, 0, 0, 0.11);
            width: 212px;
            height: 30rem;
            margin: 1rem;
            padding: 10px 5px !important;
            text-align: center !important;
        }
    }

    .product-item .price-box .old-price .price {
        font-size: 12px;
        font-weight: 300;
        font-stretch: normal;
        font-style: normal;
        line-height: 2;
        letter-spacing: normal;
        text-align: left;
        color: #797979;
        text-decoration: line-through;
        display: block !important;
    }

    .product-item .price-box {
        margin: 10px 0 25px;
        margin-bottom: 25px;
        flex-flow: column-reverse !important;
        display: flex !important;
    }

    .price-label {
        display: none;
    }
</style>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var $blockE WeltPixel\GoogleTagManager\Block\AbstractSlider;
 * @var $blockE \Magento\Catalog\Block\Product\AbstractProduct
 */
?>
<?php
$blockE = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\AbstractProduct');
$_productCollection = $block->getLoadedProductCollection();
$promotionsHelper = $this->helper('Softtek\CustomPromotions\Helper\ProductPromotionsHelper');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_helperlaber = $this->helper('Softtek\CustomPromotions\Helper\Bigpatch');
$thislabel = $_helperlaber->getLabel();

/** WeltPixel_GoogleTagManager  */
$gtmHelper = $this->helper('WeltPixel\GoogleTagManager\Helper\Data');

?>
<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else : ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <?php $items = $promotionsHelper->checkByGroup($_productCollection); ?>
        <ol class="products list items product-items">
            <?php
            function html_to_obj($html) {
                $dom = new DOMDocument();
                $dom->loadHTML($html);
                return element_to_obj($dom->documentElement);
            }
             function element_to_obj($element) {
                $obj = array( "tag" => $element->tagName );
                foreach ($element->attributes as $attribute) {
                    $obj[$attribute->name] = $attribute->value;
                }
                foreach ($element->childNodes as $subElement) {
                    if ($subElement->nodeType == XML_TEXT_NODE) {
                        $obj["html"] = $subElement->wholeText;
                    }
                    else {
                        $obj["children"][] = element_to_obj($subElement);
                    }
                }
                return $obj;
            }
            /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) : ?>
                <?php /* @escapeNotVerified */ echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <!-- Categoria -->
                    <div class="row">
                        <div class="col-sm-4 categoria-producto" align="left">
                            <?php
                            $genero = $_product->getAttributeText('genero');
                            $deporte = $_product->getAttributeText('deporte');
                            $texto = "";
                            if (is_array($genero)) {
                                if ($deporte != "") {
                                    $texto = $texto . $genero[0] . '/' . $genero[1] . '/<br>';
                                } else {
                                    $texto = $texto . $genero[0] . '/' . $genero[1];
                                }
                            } else {
                                if ($deporte != "") {
                                    $texto = $texto . $genero . '/';
                                } else {
                                    $texto = $texto . $genero;
                                }
                            }
                            if (is_array($deporte)) {
                                $texto = $texto . $deporte[0];
                            } else {
                                $texto = $texto . $deporte;
                            }
                            echo $texto;
                            ?>
                        </div>
                    </div>
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image
                    ?>
                    <!-- SPORTICO PROMOTION START CATALOG -->
                    <div class="promo-tags">
                    <?php
                            // $firstPromo = false;
                            // if(!is_null($_item->getPromoLabel1())) {
                            //     $promoStartDate1 = strtotime($_item->getPromoStartDate1());
                            //     $promoEndDate1 = strtotime($_item->getPromoEndDate1());
                            //     $currentDate = strtotime('now');
                            //     if (($currentDate >= $promoStartDate1) && ($currentDate <= $promoEndDate1)) {
                            //         $firstPromo = true;
                            //     }
                            // }
                            // $_item->getPromoLabel1()
                            $firstPromo = true;
                        ?>
                        <?php if(!empty ($_product->getPromoLabel1())) :?>
                            <span class="promo-label first-promo"><?= $_product->getPromoLabel1() ?></span>
                        <?php endif; ?>
                        <?php
                            $secondPromo = false;
                            /*if(!is_null($_item->getPromoLabel2())) {
                                $promoStartDate2 = strtotime($_item->getPromoStartDate2());
                                $promoEndDate2 = strtotime($_item->getPromoEndDate2());
                                $currentDate = strtotime('now');
                                if (($currentDate >= $promoStartDate2) && ($currentDate <= $promoEndDate2)) {
                                    $secondPromo = true;
                                }
                            }*/
                        ?>
                        <?php if(!empty ($_product->getPromoLabel2())) :?>
                            <span class="promo-label second-promo"><?= $_product->getPromoLabel2() ?></span>
                        <?php endif; ?>
                    </div>
                    <!-- SPORTICO PROMOTION END -->
                    <a <?php if ($gtmHelper->isProductClickTrackingEnabled()) :
                            echo $this->helper('WeltPixel\GoogleTagManager\Helper\Data')->addProductClick($_product, $iterator - 1);
                        endif; ?> href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="row" align="left">
                        <div class="col-sm-12 marca-nombre">
                            <?php echo $_product->getAttributeText('marca'); ?>
                        </div>
                    </div>
                    <div class="product details product-item-details" align="left">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <div class="mt-3"><?php
                        $newprice2 = html_to_obj($blockE->getProductPrice($_product));
                        //echo (json_encode($newprice2));
                             if(isset ($newprice2["children"][0]["children"][0]["children"][0]["children"][0]["data-price-amount"])){
                                 $newprice2 = $newprice2["children"][0]["children"][0]["children"][0]["children"][0]["data-price-amount"];
                             }else{
                                if(isset($newprice2["children"][0]["children"][0]["children"][1])){
                                $newprice2 = $newprice2["children"][0]["children"][0]["children"][1]["children"][0]["children"][1]["data-price-amount"];
                                }else{
                                    $newprice2 = $newprice2["children"][0]["children"][0]["children"][0]["children"][0]["children"][1]["data-price-amount"];
                                }
                            }
                            $newprice = $newprice2;
                               ?>
                                <?php
                                if(!empty ($_product->getPromoLabel1())) :?>
                                    <?php if($_product->getSimpleAction1()=="by_percent") :?>
                                        <div class="crossprice">$<?=
                                        /** @noEscape */ $newprice; ?></div>
                                     <?php
                                        $promoDiscount= $_product->getDiscountAmount1()/100;
                                        $newprice = $newprice - ($promoDiscount*$newprice);
                                        ?>
                                    <?php endif; ?>
                                    <?php if($_product->getSimpleAction1()=="by_fixed") :?>
                                        <div class="crossprice">$<?=
                                        /** @noEscape */ $newprice; ?></div>
                                     <?php
                                        $promoDiscount= $_product->getDiscountAmount1();
                                        $newprice = $newprice - $promoDiscount;
                                        ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if(!empty ($_product->getPromoLabel2())) :?>
                                    <?php if($_product->getSimpleAction2()=="by_percent") :?>
                                        <div class="crossprice">$<?=
                                        /** @noEscape */  $newprice; ?></div>
                                     <?php
                                        $promoDiscount= $_product->getDiscountAmount2()/100;
                                        $newprice = $newprice - ($promoDiscount*$newprice);
                                        ?>
                                    <?php endif; ?>
                                    <?php if($_product->getSimpleAction2()=="by_fixed") :?>
                                        <div class="crossprice">$<?=
                                        /** @noEscape */  $newprice; ?></div>
                                     <?php
                                        $promoDiscount= $_product->getDiscountAmount2();
                                        $newprice = $newprice - $promoDiscount;
                                        ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <div class = "price">$<?=
                                        /** @noEscape */  $newprice; ?></div>
                      </div>


                    </div>
                </div>
                <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
